### ISSUE TITLE
Your work is very meaningful, I would like to ask if you can provide the code under PyTorch

### ISSUE THREAD

**Issue by YangBai1109** [krishnabits001/domain_specific_cl#4]
The code you provided is based on TensorFlow, which is difficult to implement. Could you provide the code of PyTorch?

**Comment by krishnabits001** [comment]
Sorry for the delayed reply.
Unfortunately, we do not have the code in PyTorch as of now.
I will add the link to the pytorch repo in case I make one in the future.
