### ISSUE TITLE
Do you have a pre-processing on MMWHS?

### ISSUE THREAD

**Issue by ElegantLin** [krishnabits001/domain_specific_cl#5]
I did not see the MMWHS on `create_cropped_imgs.py`. Does that mean there is no need to pre-process on MMWHS?

Thanks!

**Comment by krishnabits001** [comment]
Hi Zonglin,

Yes, I do similar pre-processing on MMWHS dataset as done for ACDC and Prostate datasets.

Regards,
Krishna Chaitanya
